Assign the below variable number to the number 42 by replacing None with 42.

In [3]:

number = 42
print(number)

42


Next, like the above, reassign the flatiron_mantra variable with the string "Change Things" 

In [2]:
flatiron_mantra = "Change Things"
flatiron_mantra

'Change Things'

In [4]:
print('Hello World')

Hello World


### This is a new header

C:\Users\Administrator\Desktop\Python\.venv\lab1.ipynb

NUMPY

In [ ]:
import numpy as np

In [3]:
list=[23,45,50]
type(list)

list

In [4]:
arr=np.array([12,24,45])
type(arr)

numpy.ndarray

In [25]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
print(arr1)
arr1.ndim
print("-----\n")
print(arr2)
arr1.ndim
print("-----\n")
print(arr3)


[1 2 3 4]
-----

[[1 2 3 4]
 [5 6 7 8]]
-----

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [8]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2[0:,1]

array([2, 6])

In [10]:
arr2[0,2]

np.int64(3)

In [24]:
arr3.ndim
#type(arr3)

2

In [28]:
arr3[0:,2,2]

array([11])

converting a list to an array and joining

In [37]:
age=[1,2,3,4]
height=[5,6,7,8]
agerr=np.array(age)
eight=np.array(height)
agerr
eight

array([5, 6, 7, 8])

Arrithmetic
    multiplication

In [31]:
list*5

[23, 45, 50, 23, 45, 50, 23, 45, 50, 23, 45, 50, 23, 45, 50]

In [32]:
arr1*5

array([ 5, 10, 15, 20])

In [34]:
arr1+2

array([3, 4, 5, 6])

In [35]:
list+2

TypeError: can only concatenate list (not "int") to list

In [38]:
array1_1=np.array([5,6,7,8])
list1_1=[5,6,7,8]

array1_1+list1_1
array1_1>3

array([ True,  True,  True,  True])

In [39]:
np.mean(array1_1)

np.float64(6.5)

In [46]:
arr_n=np.array([3,4,5,6,7],ndim=3)
arr_n.ndim

TypeError: array() got an unexpected keyword argument 'ndim'